name: gen
description: A new Flutter package project.
version: 0.0.1
homepage: none

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  envied: ^0.3.0+3
  equatable: ^2.0.5
  # for network model
  vexana: ^3.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib/src/asset/
  integrations:
    lottie: true
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  assets:
    - assets/color/
    - assets/lottie/
    - assets/icons/
    - assets/images/
