name: architecture_template_v2
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Core
  equatable: ^2.0.5
  get_it: ^7.6.4

  #Network Dependencies
  vexana: ^3.5.4

  #State
  flutter_bloc: ^8.1.3

  # Config
  easy_localization: ^3.0.3

  #Utility
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  kartal: ^3.5.0
  google_fonts: ^6.1.0

  #Navigation
  auto_route: ^7.8.4

  widgets:
    path: module/widgets

  # Modules
  gen:
    path: module/gen
  common:
    path: module/common
  core:
    path: module/core

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  device_preview: ^1.1.0
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  patrol: ^2.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/translations/
